### ISSUE TITLE
Admin can no longer add events 

### ISSUE THREAD

**Issue by ahmed-wael2002** [MinaGeo/NPO-SDP#1]
![image](https://github.com/user-attachments/assets/f6623dcd-8200-48d8-a4ce-047907549398)

When clicking in add event in admin events page. this shows up. please fix.
Ignore the left part of the screenshot. I was using a dual monitor.

**Comment by rafikghaly** [comment]
Done! Please check last commit "f628619cf3df30fc8fea6e5213c050a045539339"

**Comment by ahmed-wael2002** [comment]
Thanks Eng. Rafik 
Wish u a great day

**Comment by MinaMorgan** [comment]
Eng. Ahmed Wael
I am glad to inform u that you are fired.
Have a great day

Best Regards
Mina Morgan
